apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    {{- include "fluent-bit-plugin.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.grafana.adminPassword | quote }}
